package janela;
import javax.swing.JOptionPane;
import queuestatic.QueueStatic;
/**
 *
 * @author Arthur
 */
public class Janela extends javax.swing.JFrame {
   
    QueueStatic fila = new QueueStatic(); // Criando a Propriedade Fila
    
    public Janela() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb_add = new javax.swing.JLabel();
        input_add = new javax.swing.JTextField();
        lb_capacidade = new javax.swing.JLabel();
        input_capacidade = new javax.swing.JTextField();
        btn_Setcapacidade = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_getremove = new javax.swing.JButton();
        btn_getCapacidade = new javax.swing.JButton();
        btn_getStatus = new javax.swing.JButton();
        btn_getTamanho = new javax.swing.JButton();
        btn_getFila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_saida = new javax.swing.JTextArea();
        lb_saidaDeDados = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JButton();
        btn_cretidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Fila Estática");

        lb_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_add.setText("Adicionar");

        lb_capacidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_capacidade.setText("Aumentar Capacidade");

        btn_Setcapacidade.setText("OK");
        btn_Setcapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SetcapacidadeActionPerformed(evt);
            }
        });

        btn_add.setText("OK");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_getremove.setText("Remover");
        btn_getremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getremoveActionPerformed(evt);
            }
        });

        btn_getCapacidade.setText("Capacidade da Fila");
        btn_getCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getCapacidadeActionPerformed(evt);
            }
        });

        btn_getStatus.setText("Status da Fila");
        btn_getStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getStatusActionPerformed(evt);
            }
        });

        btn_getTamanho.setText("Tamanho da Fila");
        btn_getTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getTamanhoActionPerformed(evt);
            }
        });

        btn_getFila.setText("Vê Fila");
        btn_getFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getFilaActionPerformed(evt);
            }
        });

        ta_saida.setEditable(false);
        ta_saida.setColumns(20);
        ta_saida.setRows(5);
        jScrollPane1.setViewportView(ta_saida);

        lb_saidaDeDados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_saidaDeDados.setText("Logs");

        btn_limpar.setText("Limpar Logs");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_cretidos.setText("Créditos");
        btn_cretidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cretidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cretidos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_add)
                                    .addGap(18, 18, 18)
                                    .addComponent(input_add, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_add))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_getremove)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_getStatus)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_getTamanho)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_getCapacidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_getFila))
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_capacidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(input_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Setcapacidade))))
                            .addComponent(lb_saidaDeDados))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_add)
                    .addComponent(input_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_capacidade)
                    .addComponent(input_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Setcapacidade))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_getremove)
                    .addComponent(btn_getCapacidade)
                    .addComponent(btn_getStatus)
                    .addComponent(btn_getTamanho)
                    .addComponent(btn_getFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lb_saidaDeDados)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_cretidos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            int value = Integer.parseInt(input_add.getText()); // Pegando o valor do campo input_add
            fila.add(value); // adicionado novo item na fila
            String text = value + " foi adicionado com sucesso na fila. \n"; // mensagem para ser exibida no console
            ta_saida.setText(ta_saida.getText() + text); // adicionado mensagem no console.
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(rootPane, "A Fila está cheia, tente aumentar o seu tamanho.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite apenas valores numéricos inteiros!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } finally {
            input_add.setText(""); // Limpando o campo input_add
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_SetcapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SetcapacidadeActionPerformed
        try {
            int value = Integer.parseInt(input_capacidade.getText());
            int oldCapacity = fila.getCapacity(); // Pegando o tamanho antigo da fila
            fila.resize(value); // Alterando tamanho da fila
            String text = "O tamanho da fila fou alterado de " + oldCapacity + " para " + value + ".\n"; // String que será impressa nos logs
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite apenas valores numéricos inteiros maiores que o tamanho da fila!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } finally {
            input_capacidade.setText(""); // Limpando o campo input_capacidade
        } 
    }//GEN-LAST:event_btn_SetcapacidadeActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
         ta_saida.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_getremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getremoveActionPerformed
        try {
            fila.remove(); // removendo elemento da Fila
            String text = "O Primeiro elemento da fila foi removido \n";// String que será impressa nos logs
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(rootPane, "A fial está vazia!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ops! Ocorreu um erro desconhecido.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_getremoveActionPerformed

    private void btn_getStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getStatusActionPerformed
        try {
            String text;
            if(fila.isEmpty()) { 
                text = "A fila está vazia | ";
            } else {
                text = "A fina não está vazia | ";
            }
            
            if(fila.isFull()) {
                text += "A fila está cheia.\n";
            } else {
                text += "A fila não está cheia.\n";
            }
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ops! Ocorreu um erro desconhecido.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_getStatusActionPerformed

    private void btn_getTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getTamanhoActionPerformed
        try {
            String text = "O tamanho da fila é de " + fila.size() + ".\n";
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ops! Ocorreu um erro desconhecido.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_getTamanhoActionPerformed

    private void btn_getCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getCapacidadeActionPerformed
        try {
            String text = "A capacidade da fila é de " + fila.getCapacity() + ".\n";
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
            input_capacidade.setText(""); // Limpando o campo input_capacidade
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ops! Ocorreu um erro desconhecido.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_getCapacidadeActionPerformed

    private void btn_getFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getFilaActionPerformed
        try {
            // Verificando se a Fila está vazia
            if(fila.isEmpty()) {
                throw new IllegalArgumentException();
            }
            String text = "[";
            // Realizando for para pegar todos os valores da fila
            for(int i = 0; i < fila.size(); i++) {
                text += fila.getPosition(i);
                if(i + 1 != fila.size()) text += ", ";
            }
            text += "]\n";
            ta_saida.setText(ta_saida.getText() + text); // Imprimindo mensagem
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, "A Fila está vazia.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_getFilaActionPerformed

    private void btn_cretidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cretidosActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Trabalho sobre a estrutura de dados fila estática. Referente \n à disciplina de Estrutura de Dados I, realizada pelo aluno Arthur Souza.\n \n \n Orientador: Almir D. V. Santiago - Mestre em Sistemas e Computação");
    }//GEN-LAST:event_btn_cretidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Setcapacidade;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cretidos;
    private javax.swing.JButton btn_getCapacidade;
    private javax.swing.JButton btn_getFila;
    private javax.swing.JButton btn_getStatus;
    private javax.swing.JButton btn_getTamanho;
    private javax.swing.JButton btn_getremove;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JTextField input_add;
    private javax.swing.JTextField input_capacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_add;
    private javax.swing.JLabel lb_capacidade;
    private javax.swing.JLabel lb_saidaDeDados;
    private javax.swing.JTextArea ta_saida;
    // End of variables declaration//GEN-END:variables
}
